version: "3.9"

services:
  backendApi:
    image: ahcarter22/dmw-api:latest
    environment:
      - PROD_DB_URL=${PROD_DB_URL}
      - PROD_DB_USERNAME=${PROD_DB_USERNAME}
      - PROD_DB_PASSWORD=${PROD_DB_PASSWORD}
    ports:
      - 8080:8080