###
POST http://localhost:8080/api/message HTTP/1.1

###
POST http://localhost:8080/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "sally@jones.com",
    "password": "P@ssw0rd!"
}
