@url = http://localhost:8080/api/item
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2Mzk3MTQ4OTZ9.SBDSFXdO8UkGsL7lKkQNU0cgBNdUkgRQjBF8GodI52M

POST http://localhost:8080/login HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}
###

POST http://localhost:8080/refresh_token HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJidWctc2FmYXJpIiwic3ViIjoiam9obkBzbWl0aC5jb20iLCJhdXRob3JpdGllcyI6IlJPTEVfQURNSU4iLCJleHAiOjE2Mzk3MTQ4OTZ9.SBDSFXdO8UkGsL7lKkQNU0cgBNdUkgRQjBF8GodI52M

###
GET {{url}} HTTP/1.1
//Authorization: Bearer {{token}}

###############

GET {{url}}/1 HTTP/1.1
//Authorization: Bearer {{token}}

###

POST  {{url}} HTTP/1.1
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "name": "Test",
    "quantity": 2,
    "scale": "tons",
    "expirationDate": "2021-04-04",
    "vendorId": 1,
    "categoryId": 1
}

###

PUT {{url}}/5 HTTP/1.1
Content-Type: application/json
//Authorization: Bearer {{token}}

{
    "itemId": 5,
    "name": "updated Test",
    "quantity": 2,
    "scale": "tons",
    "expirationDate": "2021-04-04",
    "vendorId": 1,
    "categoryId": 1
}



###

DELETE {{url}}/5 HTTP/1.1
//Authorization: Bearer {{token}}