@url = http://localhost:8080/api/item


GET {{url}} HTTP/1.1


###############

GET {{url}} HTTP/1.1

###

POST  {{url}} HTTP/1.1
Content-Type: application/json


{
    "name": "Test",
    "quantity": "2",
    "scale": "tons",
    "expirationDate": "2021-04-04",
    "vendorId": "1",
    "category": "PRODUCE"
}

###

DELETE {{url}}/2 HTTP/1.1